### ISSUE TITLE
Unexpected token < with nuxt.js

### ISSUE THREAD

**Issue by ghost** [mage3k/vue-feather-icon#9]
![image](https://user-images.githubusercontent.com/4539476/34470009-2be6a9b0-ef29-11e7-8913-6c1c878a1e22.png)

**plugin/feather_icon.js**
```
import Vue from 'vue'
import VueFeatherIcon from 'vue-feather-icon'

Vue.use(VueFeatherIcon)
```

**nuxt.config.js**
```
...
  plugins: [{ src: '~/plugins/feather_icon.js' }],
...
```

**Comment by carcinocron** [comment]
I have the same issue. If I try this:

```
import Vue from 'vue';
import AlertTriangleIcon from 'vue-feather-icon/components/alert-triangle';
Vue.component('AlertTriangleIcon', AlertTriangleIcon);
```
then I get this:
```
NuxtServerError
Cannot find module 'vue-feather-icon/components/alert-triangle' from '/home/forge/link-queue/app'
```
When it was working in nuxt 0.10.

**Comment by carcinocron** [comment]
This worked:
```
import AlertTriangleIcon from '~~/node_modules/vue-feather-icon/components/alert-triangle';
```

**Comment by ConsoleTVs** [comment]
May I ask what exception handler are you using for node? Thanks!

**Comment by ghost** [comment]
@InstanceOfMichael indeed 👍 - thank you

**Comment by bsthomsen** [comment]
Anyone else struggling with this you can create a nuxt plugin with the following code:

```import Vue from 'vue'
import upperFirst from 'lodash/upperFirst'
import camelCase from 'lodash/camelCase'

const requireComponent = require.context(
  '~/node_modules/vue-feather-icon/components',
  false,
  /[\w-]+\.vue$/
)

requireComponent.keys().forEach(fileName => {
  const componentConfig = requireComponent(fileName)
  const componentName =
    'Feather' + upperFirst(camelCase(fileName.replace(/\.\w+$/, '')))
  Vue.component(componentName, componentConfig.default || componentConfig)
})
```

**Comment by MarcelloTheArcane** [comment]
@bsthomsen I had to use this because the components were named like `Feather./<...>`

```js
import Vue from 'vue'

const requireComponent = require.context(
  '~/node_modules/vue-feather-icon/components',
  false,
  /[\w-]+\.vue$/
)

requireComponent.keys().forEach((fileName) => {
  const componentConfig = requireComponent(fileName)
  const componentName = 'Feather' + camelCase(fileName.replace(/(^\.\/|\.\w+$)/g, ''))
  Vue.component(componentName, componentConfig.default || componentConfig)
})

function upperFirst (string) {
  return string[0].toLocaleUpperCase() + string.slice(1)
}

function camelCase (string) {
  return string
    .toLocaleLowerCase()
    .split(/[ _-]+/g)
    .reduce((final, section) => {
      final += upperFirst(section)
      return final
    }, '')
}
```
